# Generated by Django 5.2.4 on 2025-07-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesador_de_imei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('generico', 'Genérico'), ('mojo', 'Mojo')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('imeis', models.TextField()),
            ],
        ),
    ]
