services:
  - type: web
    name: rma-recepcion
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn rma_recepcion.wsgi"
    envVars:
      - key: DATABASE_URL
        sync: false
    staticPublishPath: staticfiles
    plan: free 