# Generated by Django 5.2.4 on 2025-07-21 00:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, unique=True, verbose_name='Número de Lote')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LoteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('imei', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El IMEI debe tener exactamente 15 dígitos numéricos.', regex='^\\d{15}$')], verbose_name='IMEI')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Roto', 'Roto'), ('Mezcla', 'Mezcla'), ('Perdida', 'Perdida')], default='Nuevo', max_length=20, verbose_name='Estado')),
                ('caja_original', models.BooleanField(default=False, verbose_name='Caja Original')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='equipos.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Detalle de Lote',
                'verbose_name_plural': 'Detalles de Lote',
                'ordering': ['-fecha_ingreso'],
                'unique_together': {('lote', 'imei')},
            },
        ),
    ]
