# Generated by Django 5.2.4 on 2025-07-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cantidad_modelos',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Modelos'),
        ),
    ]
