# Generated by Django 5.2.4 on 2025-07-21 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_lote_cantidad_modelos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotedetalle',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='lotedetalle',
            name='modelo',
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Modelo de Equipo',
                'verbose_name_plural': 'Modelos de Equipo',
                'ordering': ['marca', 'modelo'],
                'unique_together': {('marca', 'modelo')},
            },
        ),
        migrations.AddField(
            model_name='lotedetalle',
            name='modelo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.modeloequipo', verbose_name='Modelo de Equipo'),
        ),
    ]
