# Generated by Django 5.2.4 on 2025-07-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_remove_lotedetalle_marca_remove_lotedetalle_modelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotedetalle',
            name='modelo_equipo',
        ),
        migrations.AddField(
            model_name='lotedetalle',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='lotedetalle',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
    ]
