# Generated by Django 5.2.4 on 2025-07-21 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_remove_lotedetalle_modelo_equipo_lotedetalle_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='equipos.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Modelo en Lote',
                'verbose_name_plural': 'Modelos en Lote',
                'ordering': ['lote', 'marca', 'modelo'],
                'unique_together': {('lote', 'marca', 'modelo')},
            },
        ),
    ]
